name: simplify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5-148.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  circular_bottom_navigation: ^2.0.0
  

  get: 4.6.5
  get_storage: ^2.0.3

  intl:
  
  material_design_icons_flutter: ^5.0.6595
  mask_text_input_formatter: ^2.3.0

  splashscreen: ^1.3.5
  validatorless: ^1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

  assets:
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/logos/GIF2.gif
   - assets/logos/GIF.gif
   - assets/screenshots/Captura_da_Web_13-6-2022_125743_.jpeg.jpg
   - assets/screenshots/preview-2.jpg
   - assets/screenshots/Screenshot_1657580136.png
   - assets/screenshots/ScreenShot012.png
   - assets/screenshots/fullwhite.gif
   - assets/logos/LogoTrello.png

